# -*- coding: utf-8 -*-
"""Mathi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ldJNEMpxEb-bsnZ6p0Fr3W_tIMawQcy
"""
from flask import*
import pickle
import numpy 

mathi=Blueprint('mathi',__name__)

@mathi.route('/',methods=["GET","POST"])
def main():

    if 'submit' in request.form:
        
        with open('model_pkl' , 'rb') as f:
            lr = pickle.load(f)

        weight = request.form.get("weight")
        length1 = request.form.get("length1")
        length2 = request.form.get("length2")
        length3 = request.form.get("length3")
        height = request.form.get("height")
        width = request.form.get("width")

        y = []
        y.append(weight)
        y.append(length1)
        y.append(length2)
        y.append(length3)
        y.append(height)
        y.append(width)

        arr = numpy.array(y,dtype = float)
        result = lr.predict([arr])

        return render_template('fish.html',result="{}".format(result[0]))

    return render_template("fish.html")
